#!/bin/sh
cd XMP_SDK/MetadataToolkit/Build/UNIX
make_release
cd ../../../../jpeglib
./configure
make
cd ..
cc -o d70reader -I ./jpeglib -D __UNIX_ONLY__ -D ALLOW_ROTATE=0 d70reader.c d70buildweb.c d70resize.c d70utils.c d70jpegtran.c ./jpeglib/cdjpeg.o ./jpeglib/rdswitch.o ./jpeglib/transupp.o ./jpeglib/libjpeg.a
cp ./d70reader ../bin/d70reader_no_rotate
rm ./d70reader
